name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]
    

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v6.4.0
      with:
        node-version: '22'
        cache: "npm"
        cache-dependency-path: ./server/package-lock.json
    - name: Install and test server
      run: |
        cd server
        npm ci
        npm test
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Set up Docker Buildx (required for modern builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      # 3. Build and Push using the official action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: chusvybe/stev:latest, chusvybe/stev:v1

